removeallActions WM;
WM addAction ["<t color='#ff1111'>Quartermaster</t>", hint ""]; 
WM addAction ["==================", hint ""];
WM addAction ["Squad 1IC","Scripts\Loadouts\Quartermaster\Infantry.sqf",[["1IC"]]];
WM addAction ["Squad 2IC","Scripts\Loadouts\Quartermaster\Infantry.sqf",[["2IC"]]];
WM addAction ["Squad Medic", "Scripts\Loadouts\Quartermaster\Infantry.sqf", [["MEDIC"]]];
WM addAction ["Squad Marksman", "Scripts\Loadouts\Quartermaster\Infantry.sqf", [["MARKSMAN"]]];
WM addAction ["Squad 249 Machine Gunner", "Scripts\Loadouts\Quartermaster\Infantry.sqf", [["249MG"]]];
WM addAction ["Squad 240 Machine Gunner", "Scripts\Loadouts\Quartermaster\Infantry.sqf", [["240MG"]]];
WM addAction ["Squad Heavy Anti-Tank", "Scripts\Loadouts\Quartermaster\Infantry.sqf", [["HAT"]]];
WM addAction ["Squad EOD", "Scripts\Loadouts\Quartermaster\Infantry.sqf", [["EOD"]]];
WM addAction ["==================", hint ""]; 
WM addAction ["<t color='#54ff9f'>Back</t>", "Scripts\Loadouts\Quartermaster\21stORBAT\back.sqf"];