removeAllActions VM;
VM addAction ["<t color='#ff1111'>Vehicle Manager</t>", hint ""]; 
VM addAction ["==================", hint ""];
VM addAction ["Spawn Coyote with GMG", "Scripts\VehicleSpawn\wheeled.sqf", [["COYGMG"]]];
VM addAction ["Spawn Coyote with HMG", "Scripts\VehicleSpawn\wheeled.sqf", [["COYHMG"]]];
VM addAction ["Spawn Jackal with GMG", "Scripts\VehicleSpawn\wheeled.sqf", [["JAKGMG"]]];
VM addAction ["Spawn Jackal with HMG", "Scripts\VehicleSpawn\wheeled.sqf", [["JAKHMG"]]];
VM addAction ["Spawn Coyote with GMG Tan", "Scripts\VehicleSpawn\wheeled.sqf", [["COYGMGTAN"]]];
VM addAction ["Spawn Coyote with HMG Tan", "Scripts\VehicleSpawn\wheeled.sqf", [["COYHMGTAN"]]];
VM addAction ["Spawn Jackal with GMG Tan", "Scripts\VehicleSpawn\wheeled.sqf", [["JAKGMGTAN"]]];
VM addAction ["Spawn Jackal with HMG Tan", "Scripts\VehicleSpawn\wheeled.sqf", [["JAKHMGTAN"]]];
VM addAction ["Spawn WMIK Milan", "Scripts\VehicleSpawn\wheeled.sqf", [["WMIKMILAN"]]];
VM addAction ["Spawn WMIK HMG", "Scripts\VehicleSpawn\wheeled.sqf", [["WMIKHMG"]]];
VM addAction ["Spawn WMIK Milan Tan", "Scripts\VehicleSpawn\wheeled.sqf", [["WMIKMILANTAN"]]];
VM addAction ["Spawn WMIK HMG Tan", "Scripts\VehicleSpawn\wheeled.sqf", [["WMIKHMGTAN"]]];
VM addAction ["Spawn Panther", "Scripts\VehicleSpawn\wheeled.sqf", [["PANTHER"]]];
VM addAction ["Spawn Panther Tan", "Scripts\VehicleSpawn\wheeled.sqf", [["PANTHERTAN"]]];
VM addAction ["==================", hint ""];
VM addAction ["<t color='#54ff9f'>Back</t>", "Scripts\VehicleSpawn\Menu\back.sqf"];